package top.bearcabbage.lanterninstorm.lantern;

import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.piston.PistonBehavior;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;

import static top.bearcabbage.lanterninstorm.LanternInStorm.MOD_ID;


public abstract class SpiritLanternBlocks {
    /*2x铁门硬度基岩爆炸抗性*/
    public static final Block CUBIC_GLASS_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"cubic_glass_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.GLASS).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK)));
    public static final Block WHITE_PAPER_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"white_paper_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.WHITE).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.LANTERN).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    // 木质立方灯
    public static final Block OAK_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"oak_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block SPRUCE_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"spruce_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block BIRCH_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"birch_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block JUNGLE_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"jungle_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block ACACIA_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"acacia_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block DARK_OAK_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"dark_oak_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block MANGROVE_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"mangrove_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block CHERRY_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"cherry_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block BAMBOO_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"bamboo_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block CRIMSON_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"crimson_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block WARPED_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"warped_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block FIR_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"fir_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block PINE_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"pine_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block MAPLE_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"maple_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block REDWOOD_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"redwood_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block MAHOGANY_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"mahogany_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block JACARANDA_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"jacaranda_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block PALM_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"palm_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block WILLOW_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"willow_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block DEAD_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"dead_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK).dropsLike(CUBIC_GLASS_LANTERN)));
    public static final Block MAGIC_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"magic_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK)));
    public static final Block UMBRAN_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"umbran_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK)));
    public static final Block HELLBARK_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"hellbark_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).nonOpaque().pistonBehavior(PistonBehavior.BLOCK)));
    public static final Block EMPYREAL_WOODEN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"empyreal_wooden_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).strength(10.0F, 3600000.0F).nonOpaque().pistonBehavior(PistonBehavior.BLOCK)));
    // 限量版彩灯
    public static final Block SNOWMAN_LANTERN = (Block) Registry.register(Registries.BLOCK, Identifier.of(MOD_ID,"snowman_lantern"), new SpiritLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).strength(10.0F, 3600000.0F).sounds(BlockSoundGroup.GLASS).luminance((state) -> {return 10;}).nonOpaque().pistonBehavior(PistonBehavior.BLOCK)));

    public static void initialize(){}
}
